### PR TITLE
kbn_searchtables-19 - Fix rows not displaying when key is not string.

### PR DESCRIPTION
**Pull request by joeyJsonar**
Fix for #19 
Also did some design changes to match 6.x better.

### CODE REVIEW

**Comment by dlumbrer** [comment]
Hi @joeyJsonar , could you replicate the PR into the 6-dev branch too?

**Comment by joeyJsonar** [comment]
@dlumbrer Done

**Comment by joeyJsonar** [comment]
@dlumbrer Hello, I'd like to follow up on this pull request.

**Comment by dlumbrer** [comment]
Im not on this at 100%, I can't review it because I'm a little busy. During this and next week I will check it, thank you very much, I'm really sorry

**Comment by dlumbrer** [comment]
Nice work @joeyJsonar :+1:

**Comment by joeyJsonar** [comment]
Nice thanks.

**Pull request merged**
