### PR TITLE
Added Case Sensitive option

### PR DESCRIPTION
**Pull request by AndreasVolkmann**
I found it really annoying that I had to write my searches case sensitive, so I decided to add an option that indicates whether the search query has to be case sensitive in order to match.

### CODE REVIEW

**Comment by dlumbrer** [comment]
Hi @goreRatzete,

Can you undo the changes of package.json?

Moreover, can you add the default value (true) for the new param "Case sensitive" into the `kbn_searchtables.js`?

Thanks!!

**Comment by AndreasVolkmann** [comment]
Alright, I reverted package and added the default. 

Hope everything is good now. 

By the way, what is your workflow for developing kibana plugins? So far I put the project in the plugin folder and increment the version everytime I make changes, then Kibana needs to recompile. Takes quite some time. Is there some better way?

**Comment by dlumbrer** [comment]
Thx @goreRatzete , I'm going to test this feature.

I launch kibana in dev mode (./bin/kibana --dev) in order to Kibana updates the changes quickly

**Comment by dlumbrer** [comment]
All ok!, good job!

Thx @goreRatzete !

**Pull request merged**
